#!/bin/sh
# elvis: modrinth -- Search Modrinth for Minecraft mods
. surfraw || exit 1
w3_usage_hook () {
    cat <<EOH
Usage: $w3_argv0 [options] [search words]...
Description:
  Search Modrinth for Minecraft mods, resource packs, and shaders.
EOH
    w3_global_usage
}
w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://modrinth.com/"
else
    escaped_args=$(w3_url_of_arg $w3_args)
    w3_browse_url "https://modrinth.com/mods?q=${escaped_args}"
fi
